---
title: Group-based causal inference methods for identifying cooperative microRNA-mRNA
  regulatory relationships in Epithelial-Mesenchymal Transition
author: "Phuc Dai Huynh"
date: "11/12/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

source("./Scripts/require_packages.R")

require.packages(c("ini"))

# Read config file
config <- read.ini('./Configs/breast_cancer_EMTmarkers.ini')

# Set JAVA_HOME so that rJava and jdx can be loaded properly
Sys.setenv(JAVA_HOME=config$env$JAVA_HOME)

require.packages(c(
  "rJava", "jdx",
  "foreach", "doParallel",
  "dplyr", "magrittr",
  "BiocManager"
))

require.bio_packages(c(
  "CancerSubtypes",
  "miRBaseConverter", "miRLAB",
  "pcalg", "Rgraphviz"
))

# If there is any error while importing grouping_using_module_network.R, 
# please ignore it since it is just an error of Rstudio.
# Solution is to update Rstudio to 1.2.5036-1 or newer.
source("./Scripts/grouping_using_module_network.R")
source("./Scripts/conditional_independence_group_test.R")
source("./Scripts/learn_group_skeleton_pc.R")
```

# Step 1: Data Preparation
```{r, include=FALSE}
# Load the normal genes dataset and the anomaly genes dataset
load(paste(config$data$anomaly, sep=""))
load(paste(config$data$normal, sep=""))

# Load scan data
scan_df <- read.csv(config$data$scan)

# ==== 1.1 Process cancer data =====
cancer.miRNAs <- matchedData$miRs
cancer.mRNAs <- matchedData$mRNAs

cancer.version <- checkMiRNAVersion(colnames(cancer.miRNAs),verbose=FALSE)

if (cancer.version != "v21") {
  # Convert miRNA names in Cancer dataset from current version (v20) to v21
  cancer.miRNAs %>%
    # Select miRNA names
    colnames() %>%
    # Convert miRNA names to premature names
    miRNA_PrecursorToMature("v21") %>%
    # Fill NA values in Mature1 by values in OriginalName
    mutate(Mature1 = ifelse(is.na(Mature1), OriginalName, Mature1)) %>%
    # Select Mature 1
    pull(Mature1) %>%
    # Convert Mature 1 to miRNA names in v21
    miRNAVersionConvert("v21") %>%
    # Fix missing values in TargetName by taking back OriginalName values
    mutate(TargetName = ifelse(is.na(TargetName), OriginalName, TargetName)) -> miRNANames_v21
  colnames(cancer.miRNAs) <- miRNANames_v21$TargetName
  remove(miRNANames_v21)
}

# Select miRNAs in cancer dataset that are also living in the scan dataset
cancer.miRNAs <- cancer.miRNAs[, colnames(cancer.miRNAs) %in% unique(scan_df$miRNAName)]


# ==== 1.2 Process normal data =====
normal.miRNAs <- BRCA_matchedData_normal_samples$miRs

normal.version <- checkMiRNAVersion(colnames(normal.miRNAs),verbose=FALSE)

if (normal.version != "v21") {
  # Convert miRNA names in Normal dataset from current version (v20) to v21
  normal.miRNAs %>%
    # Select miRNA names
    colnames() %>%
    # Convert miRNA names to premature names
    miRNA_PrecursorToMature("v21") %>%
    # Fill NA values in Mature1 by values in OriginalName
    mutate(Mature1 = ifelse(is.na(Mature1), OriginalName, Mature1)) %>%
    # Select Mature 1
    pull(Mature1) %>%
    # Convert Mature 1 to miRNA names in v21
    miRNAVersionConvert("v21") %>%
    # Fix missing values in TargetName by taking back OriginalName values
    mutate(TargetName = ifelse(is.na(TargetName), OriginalName, TargetName)) -> miRNANames_v21
  colnames(normal.miRNAs) <- miRNANames_v21$TargetName
  remove(miRNANames_v21)
}

# Select miRNAs in cancer dataset that are also living in the scan dataset
normal.miRNAs <- normal.miRNAs[, colnames(normal.miRNAs) %in% unique(scan_df$miRNAName)]


# ==== 1.3 Merge duplications =====
# There are some duplications in cancer.miRNAs, therefore those duplications
# will be merged together by taking means.
miRNA_names <- colnames(cancer.miRNAs)

duplicated_miRNAs <- unique(miRNA_names[duplicated(miRNA_names)])

for (duplicated_miRNA in duplicated_miRNAs) {
  # Get column names again as the matrix sinks after a loops
  miRNA_names <- colnames(cancer.miRNAs)
  # Find duplicated's column index
  col_index <- which(miRNA_names == duplicated_miRNA)
  # Merge them by taking row means
  merged <- as.matrix(rowMeans(cancer.miRNAs[, col_index]))
  # Set column name
  colnames(merged) <- duplicated_miRNA
  # Reassign merged at first column index
  cancer.miRNAs[, col_index[1]] <- merged
  # Discard the rest in column index
  cancer.miRNAs <- cancer.miRNAs[,-col_index[2:length(col_index)]]
}

# ==== 1.4 Markers =====
emt_markers_df <- read.csv(config$data$emtmarker,header = F)

# Epithelial markers
emt_markers_df %>%
  dplyr::filter(V2 == 'Pro-epithelial') %>%
  mutate(miRNA = paste('hsa-', V1, sep='')) %>%
  pull(miRNA) %>%
  # Convert Mature 1 to miRNA names in v21
  miRNAVersionConvert("v21") %>%
  # Fix missing values in TargetName by taking back OriginalName values
  mutate(TargetName = ifelse(is.na(TargetName), OriginalName, TargetName)) %>%
  # Only select markers that also appear in cancer dataset
  dplyr::filter(TargetName %in% miRNA_names) %>%
  pull(TargetName) -> epi_markers

write.csv(as.data.frame(epi_markers), 
          file=config$output$epiMarkers, 
          col.names = F,
          row.names = F)

# Mesenchymal markers
emt_markers_df %>%
  dplyr::filter(V2 == 'Pro-mesenchymal') %>%
  mutate(miRNA = paste('hsa-', V1, sep='')) %>%
  pull(miRNA) %>%
  # Convert Mature 1 to miRNA names in v21
  miRNAVersionConvert("v21") %>%
  # Fix missing values in TargetName by taking back OriginalName values
  mutate(TargetName = ifelse(is.na(TargetName), OriginalName, TargetName)) %>%
  # Only select markers that also appear in cancer dataset
  dplyr::filter(TargetName %in% miRNA_names) %>%
  pull(TargetName) -> mes_markers

write.csv(as.data.frame(mes_markers), 
          file=config$output$mesMarkers, 
          col.names = F,
          row.names = F)

# Both
emt_markers_df %>%
  dplyr::filter(V2 == 'Both') %>%
  mutate(miRNA = paste('hsa-', V1, sep='')) %>%
  pull(miRNA) %>%
  # Convert Mature 1 to miRNA names in v21
  miRNAVersionConvert("v21") %>%
  # Fix missing values in TargetName by taking back OriginalName values
  mutate(TargetName = ifelse(is.na(TargetName), OriginalName, TargetName)) %>%
  # Only select markers that also appear in cancer dataset
  dplyr::filter(TargetName %in% miRNA_names) %>%
  pull(TargetName) -> both_markers

write.csv(as.data.frame(both_markers), 
          file=config$output$bothMarkers, 
          col.names = F,
          row.names = F)
```

# Step 2: Grouping
```{r, include = F}
# ==== 2.1 Grouping top 30 miRNAs using Module Network =====
epi_marker_groups <- grouping_using_module_network(jarPath = './Lib/modulenetwork/module.jar', 
                              rawData = cancer.miRNAs[, epi_markers],
                              numModules = 6,
                              numIterations = 30)

# ==== 2.2 Grouping top 30 miRNAs using Module Network =====
mes_marker_groups <- grouping_using_module_network(jarPath = './Lib/modulenetwork/module.jar', 
                              rawData = cancer.miRNAs[, mes_markers],
                              numModules = 3,
                              numIterations = 30)

# ==== 2.3 Grouping top 30 miRNAs using Module Network =====
both_marker_groups <- grouping_using_module_network(jarPath = './Lib/modulenetwork/module.jar', 
                              rawData = cancer.miRNAs[, both_markers],
                              numModules = 2,
                              numIterations = 30)


epi_groups <- grouping_using_module_network(jarPath = './Lib/modulenetwork/module.jar', 
                              rawData = cancer_dm[, epithelial],
                              numModules = 5,
                              numIterations = 30)

mes_groups <- grouping_using_module_network(jarPath = './Lib/modulenetwork/module.jar', 
                              rawData = cancer_dm[, mesenchymal],
                              numModules = 5,
                              numIterations = 30)

# Save results
save(epi_marker_groups, file=config$output$epiMarkersGroups)
save(mes_marker_groups, file=config$output$mesMarkersGroups)
save(both_marker_groups, file=config$output$bothMarkersGroups)
```

# Step 3: Learning group DAG
```{r, include=F}

# ==== 1.5 Cancer data for the experiment ====
cancer_dm <- cbind(cancer.miRNAs[, epi_markers], 
                   cancer.mRNAs[, epithelial], 
                   cancer.mRNAs[, mesenchymal])

# ==== 3.1 Learn the variable DAG
pdag <- pc(list(C = cor(cancer_dm), 
                n = nrow(cancer_dm)),
           indepTest = gaussCItest,
           alpha = 0.05,
           p = ncol(cancer_dm))

saveRDS(pdag, config$output$epiMarkersVariableDag)

learned_dag <- pdag2dag(pdag@graph)
learned_dag <- as(learned_dag$graph, "graphNEL")

# ==== 3.1 Learn the group DAG skeleton
groups <- c(
    convert_to_col_numbers(epi_marker_groups, cancer_dm),
    convert_to_col_numbers(epi_groups, cancer_dm),
    convert_to_col_numbers(mes_groups, cancer_dm)
  )
# 01:00 AM
groupDAG <- learn_skeleton_group_pc(
  dag = learned_dag,
  groups =  groups,
  ratio = 0.90,
  p = length(groups),
  numCores = 10,
  verbose = T
)

saveRDS(groupDAG, config$output$epiMarkersGroupDag)
```

```{r, include=F}

# ==== 1.5 Cancer data for the experiment ====
cancer_dm <- cbind(cancer.miRNAs[, mes_markers], 
                   cancer.mRNAs[, epithelial], 
                   cancer.mRNAs[, mesenchymal])

# ==== 3.1 Learn the variable DAG
pdag <- pc(list(C = cor(cancer_dm), 
                n = nrow(cancer_dm)),
           indepTest = gaussCItest,
           alpha = 0.05,
           p = ncol(cancer_dm))

saveRDS(pdag, config$output$mesMarkersVariableDag)

learned_dag <- pdag2dag(pdag@graph)
learned_dag <- as(learned_dag$graph, "graphNEL")

# ==== 3.1 Learn the group DAG skeleton
groups <- c(
    convert_to_col_numbers(mes_marker_groups, cancer_dm),
    convert_to_col_numbers(epi_groups, cancer_dm),
    convert_to_col_numbers(mes_groups, cancer_dm)
  )
# 07:25 AM
groupDAG <- learn_skeleton_group_pc(
  dag = learned_dag,
  groups =  groups,
  ratio = 0.90,
  p = length(groups),
  numCores = 10,
  verbose = T
)

saveRDS(groupDAG, config$output$mesMarkersGroupDag)
```


```{r, include=F}

# ==== 1.5 Cancer data for the experiment ====
cancer_dm <- cbind(cancer.miRNAs[, both_markers], 
                   cancer.mRNAs[, epithelial], 
                   cancer.mRNAs[, mesenchymal])

# ==== 3.1 Learn the variable DAG
pdag <- pc(list(C = cor(cancer_dm), 
                n = nrow(cancer_dm)),
           indepTest = gaussCItest,
           alpha = 0.05,
           p = ncol(cancer_dm))

saveRDS(pdag, config$output$bothMarkersVariableDag)

learned_dag <- pdag2dag(pdag@graph)
learned_dag <- as(learned_dag$graph, "graphNEL")

# ==== 3.1 Learn the group DAG skeleton
groups <- c(
    convert_to_col_numbers(both_marker_groups, cancer_dm),
    convert_to_col_numbers(epi_groups, cancer_dm),
    convert_to_col_numbers(mes_groups, cancer_dm)
  )
# 07:25 AM
groupDAG <- learn_skeleton_group_pc(
  dag = learned_dag,
  groups =  groups,
  ratio = 0.90,
  p = length(groups),
  numCores = 10,
  verbose = T
)

saveRDS(groupDAG, config$output$bothMarkersGroupDag)
```


























