---
title: "TF-mRNAs"
author: "Phuc Dai Huynh"
date: "11/30/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

source("./Scripts/require_packages.R")

require.packages(c("ini", 'readxl', 'openxlsx', 'dplyr'))

require.bio_packages(c('org.Hs.eg.db', 'AnnotationFuncs'))

# Read config file
config <- read.ini('./Configs/tf_mRNAs.ini')
```

```{r}
# ==== 1. Load groups ====
load(file=config$groups$epigroups)
load(file=config$groups$mesgroups)

# ==== 2. Load databases ====
tfs <- read.csv(config$databases$hg19)

ppi_db <- read_xls(config$databases$PPI, sheet='S6')
ppi_db %>%
  dplyr::rename(input = 'Input-node Gene Symbol',
         output = 'Output-node Gene Symbol') %>%
  dplyr::select(input, output) -> ppi_db

trrust_db <- read.table(config$databases$TRRUST, sep='\t', header=F)
trrust_db %>%
  dplyr::rename(input = V1,
         output = V2) %>%
  dplyr::select(input, output) -> trrust_db

load(file=config$databases$STRING)
load(file=config$databases$Reactome)
load(file=config$databases$TRED)
load(file=config$databases$ENCODE)
```


```{r}
get_tf <- function(groups) {
  results <- list()
  for (group in groups) {
    tfs %>%
      dplyr::filter(Symbol %in% group) %>%
      pull(Symbol) -> result
  
    results[[length(results) + 1]] <- result
  }
  return(results)
}

get_tf_binding_genes <- function(groups, database) {
  results <- list()
  
  for (group in groups) {
    if (!is.na(as.integer(names(database)[1]))) {
      tfs %>%
        dplyr::filter(Symbol %in% group) %>%
        pull(EntrezGene) -> entrez_id
      
      matched_entrez_id <-
        names(database)[which(names(database) %in% c(as.character(entrez_id)))]
    } else {
      print(names(database))
      print(group)
      matched_entrez_id <-
        names(database)[which(names(database) %in% c(as.character(group)))]
    }
    
    if (length(matched_entrez_id) == 0) {
      results[[length(results) + 1]] <- vector()
      next
    }
    validated_binding <- database[[matched_entrez_id]]
    
    result <- as.vector(unlist(translate(validated_binding, org.Hs.egSYMBOL)))
    
    results[[length(results) + 1]] <- result
  }
  
  return(results)
}

validate_internal_TF_mRNA <- function(tf_groups, gene_groups, database) {
  results <- list()
  for (i in (1:(length(tf_groups)))) {
    for (j in 1:length(gene_groups)) {
      if (i != j) {
        print(paste(i, '-', j))
        # print(tf_groups[[i]])
        database  %>%
          dplyr::filter((input %in% tf_groups[[i]]) &
                           (output %in% gene_groups[[j]])) -> result
        
        results[[length(results) + 1]] <- result
      }
    }
  }
  
  return(results)
}

validate_internal_TF_mRNA_by_entrezids <- function(tf_groups, gene_groups, database) {
  results <- list()
  
  bindings <- get_tf_binding_genes(tf_groups, database)
  for (i in (1:(length(bindings)))) {
    for (j in 1:length(gene_groups)) {
      if (i != j) {
        print(paste(i, '-', j))
        result <- gene_groups[[j]][which(gene_groups[[j]] %in% bindings[[i]])]
        results[[length(results) + 1]] <- result
      }
    }
  }
  
  return(results)
}

validate_internal_TF_mRNA_by_name_entrezid_database <- function(tf_groups, gene_groups, database) {
  results <- list()
  
  tfs <- names(database)
  for (i in (1:(length(tf_groups)))) {
    for (j in 1:length(gene_groups)) {
      if (i != j) {
        print(paste(i, '-', j))
        result <- list()
        tf_group <- tf_groups[[i]]
        matched_tfs <- tfs[which(tfs %in% tf_group)]
        for (matched_tf in matched_tfs) {
          mRNAs <- as.vector(unlist(translate(database[[matched_tf]], org.Hs.egSYMBOL)))
          matched_mRNAs <- mRNAs[which(mRNAs %in% gene_groups[[j]])]
          if (length(matched_mRNAs) > 0) {
            result[[matched_tf]] <- matched_mRNAs
          }
        }
        results[[length(results) + 1]] <- result
      }
    }
  }
  
  
  return(results)
}

write_dataframe_to_excel <- function(path, results, group_length) {
  i <- 1
  j <- 2
  
  wb <- createWorkbook()
  
  for(group in results) {
    names(group) <- c('TF', 'mRNA')
    
    sheetName <- paste('Group',i,'_', 'Group', j)
    addWorksheet(wb, sheetName)
    writeData(wb, sheetName, as.matrix(group))
    
    j <- j + 1
    if (j > group_length) {
      j <- 1
      i <- i + 1
    }
    if (j == i) j <- j + 1
  }
  
  saveWorkbook(wb, path, overwrite = T)
}

write_lists_to_excel <- function(path, results, group_length) {
  dataframes <- list()
  
  for (result_list in results) {
    df <- data.frame(matrix(ncol=2, nrow=0))
    if (length(result_list) > 0) {
      tf <- names(result_list)
      for (mRNA in result_list[[1]]) {
        print(paste(tf, '-', mRNA))
        df <- rbind(df, c(tf, mRNA))
      }
    }
    
    dataframes[[length(dataframes) + 1]] <- df
  }
  
  write_dataframe_to_excel(path, dataframes, group_length)
}
```

```{r}
tf_in_epi_groups <- get_tf(epi_groups)
tf_in_epi_groups

# epi_group_binding_ppi <- validate_internal_TF_mRNA(tf_in_epi_groups, epi_groups, ppi_db)
# epi_group_binding_ppi

epi_group_binding_trrust <- validate_internal_TF_mRNA(epi_groups, epi_groups, trrust_db)
epi_group_binding_trrust
write_dataframe_to_excel(config$output$epiTRRUST, epi_group_binding_trrust, length(epi_groups))

# epi_group_binding_string <- validate_internal_TF_mRNA_by_entrezids(tf_in_epi_groups, epi_groups, String_Gene_Gene)
# epi_group_binding_string

# epi_group_binding_reactome <- validate_internal_TF_mRNA_by_entrezids(tf_in_epi_groups, epi_groups, Reactome_Gene_Gene)
# epi_group_binding_reactome

epi_group_binding_encode <- validate_internal_TF_mRNA_by_name_entrezid_database(epi_groups, epi_groups, ENCODE)
epi_group_binding_encode
write_lists_to_excel(config$output$epiENCODE, epi_group_binding_encode, length(epi_groups))

epi_group_binding_tred <- validate_internal_TF_mRNA_by_name_entrezid_database(epi_groups, epi_groups, TRED)
epi_group_binding_tred
write_lists_to_excel(config$output$epiTRED, epi_group_binding_tred, length(epi_groups))
```

```{r}
tf_in_mes_groups <- get_tf(mes_groups)
tf_in_mes_groups

# mes_group_binding_ppi <- validate_internal_TF_mRNA(tf_in_mes_groups, mes_groups, ppi_db)
# mes_group_binding_ppi
# 
mes_group_binding_trrust <- validate_internal_TF_mRNA(mes_groups, mes_groups, trrust_db)
mes_group_binding_trrust
write_dataframe_to_excel(config$output$mesTRRUST, mes_group_binding_trrust, length(mes_groups))

# 
# mes_group_binding_string <- validate_internal_TF_mRNA_by_entrezids(tf_in_mes_groups, mes_groups, String_Gene_Gene)
# mes_group_binding_string
# 
# mes_group_binding_reactome <- validate_internal_TF_mRNA_by_entrezids(tf_in_mes_groups, mes_groups, Reactome_Gene_Gene)
# mes_group_binding_reactome
# 
# mes_group_binding_reactome <- validate_internal_TF_mRNA_by_entrezids(tf_in_mes_groups, mes_groups, Reactome_Gene_Gene)
# mes_group_binding_reactome

mes_group_binding_encode <- validate_internal_TF_mRNA_by_name_entrezid_database(mes_groups, mes_groups, ENCODE)
mes_group_binding_encode
write_lists_to_excel(config$output$mesENCODE, mes_group_binding_encode, length(mes_groups))

mes_group_binding_tred <- validate_internal_TF_mRNA_by_name_entrezid_database(mes_groups, mes_groups, TRED)
mes_group_binding_tred
write_lists_to_excel(config$output$mesTRED, mes_group_binding_tred, length(mes_groups))
```
```